# Development configuration - Using multiple .env files
services:
  postgres:
    image: postgres:15-alpine
    container_name: family-board-db
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-familyboard}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    container_name: family-board-backend
    ports:
      - "${BACKEND_PORT:-3001}:3001"
    env_file:
      - .env                    # Infrastructure variables
      - ./backend/.env          # Backend-specific variables
    environment:
      # Override DATABASE_URL to use Docker service name
      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/${POSTGRES_DB:-familyboard}
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - backend-node-modules:/app/node_modules
    command: npm run dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: family-board-frontend
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    env_file:
      - ./frontend/.env.development  # Development environment variables
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - frontend-node-modules:/app/node_modules
    command: npm run dev

volumes:
  postgres_data:
  backend-node-modules:
  frontend-node-modules: