/**
 * PRODUCTION CONFIGURATION - HARDCODED URLS
 * NO ENVIRONMENT VARIABLES - JUST PRODUCTION URLS
 */

// HARDCODED PRODUCTION URLS - NO LOCALHOST ANYWHERE
export const API_BASE_URL = 'https://mabt.eu';
export const SOCKET_BASE_URL = 'https://mabt.eu';
