version: '3.8'

services:
  devcontainer:
    build:
      context: ..
      dockerfile: Dockerfile.dev
    volumes:
      # Mount the entire workspace
      - ..:/workspace:cached
      # Persist bash history
      - bashhistory:/commandhistory
      # Persist extensions and VS Code server
      - vscode-extensions:/home/developer/.vscode-server/extensions
      - vscode-extensions-insiders:/home/developer/.vscode-server-insiders/extensions
      # Node modules volumes for better performance
      - backend-node-modules:/workspace/backend/node_modules
      - frontend-node-modules:/workspace/frontend/node_modules
      - mobile-node-modules:/workspace/mobile/node_modules
      - e2e-node-modules:/workspace/e2e-tests/node_modules
    
    # Override the default command
    command: sleep infinity
    
    # Environment variables
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/family_board
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    
    # Ensure we can connect to other services
    depends_on:
      - postgres
    
    # Add capabilities for debugging
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    
    # Network mode to access all services
    networks:
      - default

volumes:
  bashhistory:
  vscode-extensions:
  vscode-extensions-insiders:
  backend-node-modules:
  frontend-node-modules:
  mobile-node-modules:
  e2e-node-modules: